### ISSUE TITLE
How to produce .bag file from KITTI raw data ?

### ISSUE THREAD

**Issue by Oofs** [ethz-asl/segmap#100]
Hi SegMap team,

  Could you please share the scripts to create the bag file from raw data of KITTI ? like yours:   
  2011_09_30_drive_18.bag
  2011_10_03_drive_27.bag
  I want to test segmap on the other sequence of KITTI to evaluate the performance. Also, I notice that there are 2 topics named **/pose_imu** and **/transform_imu** in your demo bag file, are they indispensable ?

Sincerely,
Claude

**Comment by smauq** [comment]
Sorry for the late answer, but there's a few tools out there for this. For example
https://github.com/ethz-asl/kitti_to_rosbag
https://github.com/tomas789/kitti2bag

As for the IMU, we don't use one.

**Comment by Oofs** [comment]
I have figured it out. Thanks anyway!

**Comment by david-villagra** [comment]
Hi, I was having the same question. How did you convert the raw data from the KITTI dataset into a pose_imu and transform_imu? Are you implementing an odometry algorithm to get pose from the IMU raw measurements? Thanks!
