### ISSUE TITLE
Could this code support tensorflow 1.4?

### ISSUE THREAD

**Issue by songjiaxina** [ethz-asl/segmap#101]
Hello,Thanks for great work. I want to know whether this code support tf-1.4, because changing the cuda-version is painful. Thanks a lot !

**Comment by smauq** [comment]
Yes, shouldn't be a problem as most of the code was developed on an even earlier release of tf. I think the only things you will need to change is `tf.nn.softmax_cross_entropy_with_logits_v2` to `tf.nn.softmax_cross_entropy_with_logits` in [here](https://github.com/ethz-asl/segmap/blob/master/segmappy/segmappy/models/model_groups_tf.py#L112) and [here](https://github.com/ethz-asl/segmap/blob/master/segmappy/bin/segmappy_train_semantics#L116).
