### ISSUE TITLE
transform

### ISSUE THREAD

**Issue by chennuo0125-HIT** [ethz-asl/segmap#104]
![](/home/ubuntu/Pictures/Selection_002.png)
what is the difference between W_T_a_b and T_a_b ?

**Comment by danieldugas** [comment]
Hi, do you mind linking to the line of code you are referring to? thanks!

**Comment by chennuo0125** [comment]
![image](/home/ubuntu/Pictures/Selection_003.png)

**Comment by chennuo0125** [comment]
[](https://github.com/ethz-asl/laser_slam/blob/master/laser_slam/src/incremental_estimator.cpp) #L83 L86

**Comment by chennuo0125** [comment]
@danieldugas thanks for your replying, please see:
https://github.com/ethz-asl/laser_slam/blob/master/laser_slam/src/incremental_estimator.cpp#L83
https://github.com/ethz-asl/laser_slam/blob/master/laser_slam/src/incremental_estimator.cpp#L86

**Comment by smauq** [comment]
The transformations there are:
T_w_a = World frame to frame A
T_w_b = World frame to frame B
w_T_a_b = How much we'd have to move the world frame for frame B to be in the correct position
a_T_a_b = Therefore this is the transform from frame A to where frame B should be

**Comment by chennuo0125** [comment]
@smauq thanks for your answer, i get it !
