### ISSUE TITLE
Catkin build error

### ISSUE THREAD

**Issue by work4it** [ethz-asl/segmap#105]
Hello,
i followed the installation instructions. Everything worked out.
But when I ran the command **_$ catkin build segmapper_**, I got the same error as in the following post:
https://github.com/ethz-asl/voxblox/issues/177
I could solve this problem with the command **_sudo apt-get install autoconf_**.
Unfortunately, a new error appears now. Can someone help me with this?

I use Ubuntu 16.04 and ROS Kinetic.

`Errors     << laser_slam_ros:make /home/michael/segmap_ws/logs/laser_slam_ros/build.make.003.log
Traceback (most recent call last):`
`File "/opt/ros/kinetic/share/genpy/cmake/../../../lib/genpy/gensrv_py.py", line 43, in <module>
import genpy.generator`
`File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I`
` File "/opt/ros/kinetic/lib/python2.7/dist-packages/genpy/message.py", line 44, in <module>
    import yaml`
`ImportError: No module named yaml`
`make[2]: *** [/home/michael/segmap_ws/devel/lib/python2.7/dist-packages/laser_slam_ros/srv/_GetLaserTrackSrv.py] Fehler 1`
`make[1]: *** [CMakeFiles/laser_slam_ros_generate_messages_py.dir/all] Fehler 2`
`make: *** [all] Fehler 2`
`cd /home/michael/segmap_ws/build/laser_slam_ros; catkin build --get-env laser_slam_ros | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -`

`Failed     << laser_slam_ros:make                [ Exited with code 2 ]`
`Failed    <<< laser_slam_ros                     [ 0.3 seconds ]`
`Abandoned <<< segmatch_ros                       [ Unrelated job failed ]`
`Abandoned <<< segmapper                          [ Unrelated job failed ]`

`[build] Summary: 20 of 23 packages succeeded.`
`[build]   Ignored:   9 packages were skipped or are blacklisted. `
`[build]   Warnings:  4 packages succeeded with warnings.`
`[build]   Abandoned: 2 packages were abandoned.`
`[build]   Failed:    1 packages failed. `

**Comment by smauq** [comment]
The error message seems to be this one `ImportError: No module named yaml`. Try doing `pip install yaml` and see if it fixes it.

**Comment by danieldugas** [comment]
A quick google search mentions that the solution is to run:
```pip install pyyaml```

**Comment by work4it** [comment]
Thank you very much. 
With the command `pip install pyyaml` it works :)
