### ISSUE TITLE
tf_graph_executor/src/tf_graph_executor.cpp:8:44: fatal error: tensorflow/core/public/session.h: No such file or directory

### ISSUE THREAD

**Issue by chowkamlee81** [ethz-asl/segmap#113]
After executing catkin build segmapper, got the error below. KIndly help

Errors     << tf_graph_executor:make /home/administrator/segmap_ws/logs/tf_graph_executor/build.make.007.log
/home/administrator/segmap_ws/src/segmap/tf_graph_executor/src/tf_graph_executor.cpp:8:44: fatal error: tensorflow/core/public/session.h: No such file or directory
compilation terminated.
make[2]: *** [CMakeFiles/tf_graph_executor.dir/src/tf_graph_executor.cpp.o] Error 1
make[1]: *** [CMakeFiles/tf_graph_executor.dir/all] Error 2
make: *** [all] Error 2
cd /home/administrator/segmap_ws/build/tf_graph_executor; catkin build --get-env tf_graph_executor | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << tf_graph_executor:make             [ Exited with code 2 ]        
Failed    <<< tf_graph_executor                  [ 1.7 seconds ]               
Abandoned <<< libpointmatcher_ros                [ Unrelated job failed ]      
Abandoned <<< mincurves                          [ Unrelated job failed ]      
Abandoned <<< laser_slam                         [ Unrelated job failed ]      
Abandoned <<< laser_slam_ros                     [ Unrelated job failed ]      
Abandoned <<< segmatch                           [ Unrelated job failed ]      
Abandoned <<< segmatch_ros                       [ Unrelated job failed ]      
Abandoned <<< segmapper                          [ Unrelated job failed ]      
_______________________________________________________________________________

**Comment by smauq** [comment]
You need to `catkin clean` and rebuild to see the output. Otherwise the package is already built and will be skipped.

**Comment by chowkamlee81** [comment]
Hai,
Since catkin build tensorflow_ros_cpp got build, now i executed 
catkin build segmapper, i got error below: KIndly help

Finished  <<< gflags_catkin                      [ 0.2 seconds ]               
Starting  >>> glog_catkin                                                      
Finished  <<< metis_catkin                       [ 0.2 seconds ]               
Finished  <<< tensorflow_catkin                  [ 0.3 seconds ]               
Starting  >>> tensorflow_ros_cpp                                               
_______________________________________________________________________________
Errors     << eigen_catkin:cmake /home/administrator/segmap_ws/logs/eigen_catkin/build.cmake.002.log
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:297 (message):
  catkin_package() absolute include dir
  '/home/administrator/segmap_ws/build/tensorflow_catkin/tensorflow_build//home/administrator/segmap_ws/build/tensorflow_catkin/tensorflow_build/external/eigen_archive'
  does not exist
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  /home/administrator/segmap_ws/devel/share/catkin_simple/cmake/catkin_simple-extras.cmake:214 (catkin_package)
  CMakeLists.txt:104 (cs_export)


cd /home/administrator/segmap_ws/build/eigen_catkin; catkin build --get-env eigen_catkin | catkin env -si  /usr/local/bin/cmake /home/administrator/segmap_ws/src/eigen_catkin --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/administrator/segmap_ws/devel -DCMAKE_INSTALL_PREFIX=/home/administrator/segmap_ws/install -DCMAKE_BUILD_TYPE=Release; cd -
...............................................................................
Failed     << eigen_catkin:cmake                 [ Exited with code 1 ]        
Failed    <<< eigen_catkin                       [ 1.0 seconds ]               
Abandoned <<< eigen_checks                       [ Unrelated job failed ]      
Abandoned <<< libpointmatcher                    [ Unrelated job failed ]      
Abandoned <<< libpointmatcher_ros                [ Unrelated job failed ]      
Abandoned <<< gtsam_catkin                       [ Unrelated job failed ]      
Abandoned <<< minkindr                           [ Unrelated job failed ]      
Abandoned <<< minkindr_gtsam                     [ Unrelated job failed ]      
Abandoned <<< mincurves                          [ Unrelated job failed ]      
Abandoned <<< laser_slam                         [ Unrelated job failed ]      
Abandoned <<< laser_slam_ros                     [ Unrelated job failed ]      
Abandoned <<< tf_graph_executor                  [ Unrelated job failed ]      
Abandoned <<< segmatch                           [ Unrelated job failed ]      
Abandoned <<< segmatch_ros                       [ Unrelated job failed ]      
Abandoned <<< segmapper                          [ Unrelated job failed ]      
_______________________________________________________________________________
Warnings   << libnabo:install /home/administrator/segmap_ws/logs/libnabo/build.install.001.log
warning: Tag `SYMBOL_CACHE_SIZE' at line 289 of file `/home/administrator/segmap_ws/build/libnabo/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `SHOW_DIRECTORIES' at line 473 of file `/home/administrator/segmap_ws/build/libnabo/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `HTML_ALIGN_MEMBERS' at line 799 of file `/home/administrator/segmap_ws/build/libnabo/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `XML_SCHEMA' at line 1136 of file `/home/administrator/segmap_ws/build/libnabo/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: Tag `XML_DTD' at line 1142 of file `/home/administrator/segmap_ws/build/libnabo/Doxyfile' has become obsolete.
         To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
warning: doxygen no longer ships with the FreeSans font.
You may want to clear or change DOT_FONTNAME.
Otherwise you run the risk that the wrong font is being used for dot generated

**Comment by chowkamlee81** [comment]
Problem is happening with eigen_catkin path, kindly help where to resolve this issue in cmakelists

**Comment by chowkamlee81** [comment]
after doing catkin clean , got build the segmap successfully
