### ISSUE TITLE
IncrementalEuclidean memory crash

### ISSUE THREAD

**Issue by BrunoEduardoCSantos** [ethz-asl/segmap#146]
Hi,
I try to use segmenter type  IncrementalSmoothConstraints and it worked perfectly fine. Although, for some reason using IncrementalEuclidean lead to a memory crash as follows:
![error](https://user-images.githubusercontent.com/3111976/57862640-9a887000-77f0-11e9-8c79-c52a55f80d90.png)
The issue is in **growRegions**  method. Anyone had the same issue?
Thanks,
Bruno

**Comment by BrunoEduardoCSantos** [comment]
Apparently **getPointClusterId** get out of range, eventually because I don't an assigned correct ed_cluster_id. Is there way to correct this in the code?

**Comment by BrunoEduardoCSantos** [comment]
It was a problem with **ed_cluster_id**  field of MapPoint. I did an hack in region growing policy by replacing by the sc_cluster_id in set and get cluster id. Not sure if it is the right approach but it fixes it.

**Comment by jianrui1** [comment]
hi, i have the same problem as you met. Like:


Failed to find match for field 'ed_cluster_id'.ion: 0.000000 / 137.842093               
Failed to find match for field 'sc_cluster_id'.
I0916 14:28:30.037210 23323 segmatch.cpp:152] Removing too near segments from source map.
I0916 14:28:30.195529 23643 segmapper.cpp:121] publishing local maps42093               
[ WARN] [1568625089.479056936, 1317639668.207645304]: [SegMapper] Timeout while waiting between world and velodyne.

Can you help me out. Can you share your approach specifically to me?
Thanks for advance.
