### ISSUE TITLE
Failed to find match for field 'ed_cluster_id'

### ISSUE THREAD

**Issue by Lachiven** [ethz-asl/segmap#155]
when I use my own pcd file to run location of segmap
it has problem like this
[ INFO] [1585830123.605698877]: Loading target cloud.
I0402 20:22:03.605757 20090 utilities.hpp:24] Loading cloud: /home/zlj/drive.pcd.
Failed to find match for field 'ed_cluster_id'.
Failed to find match for field 'sc_cluster_id'.
I0402 20:22:24.123062 20090 segmatch.cpp:152] Removing too near segments from source map.
I0402 20:22:24.420912 20416 segmapper.cpp:121] publishing local maps

and there won't have more information and the rviz showed like this
![image](https://user-images.githubusercontent.com/50506731/78249931-b6d4ee80-7521-11ea-9737-909e7e11deec.png)
@rdube

**Comment by Lachiven** [comment]
also have the same problem when i use the example PCD file
[ INFO] [1585831197.689696114]: Number of laser_slam workers: 1
I0402 20:39:57.690075 23436 segmapper.cpp:86] Robot 0 subscribes to /velodyne_points world and velodyne
I0402 20:39:57.690119 23436 segmapper.cpp:89] Robot 0 publishes to trajectory and local_map
[ INFO] [1585831197.716211162]: Loading target cloud.
I0402 20:39:57.716262 23436 utilities.hpp:24] Loading cloud: /home/zlj/drive27_target_map.pcd.
Failed to find match for field 'ed_cluster_id'.
Failed to find match for field 'sc_cluster_id'.
I0402 20:40:31.319193 23436 segmatch.cpp:152] Removing too near segments from source map.
I0402 20:40:31.512969 23769 segmapper.cpp:121] publishing local maps

**Comment by Lachiven** [comment]
sloved when I change the  <node name="player" pkg="rosbag" type="play" output="screen" args=" -r $(arg play_rate) -s 10 --clock --pause $(arg bag_file)"/>

**Comment by FirasAbiFarraj** [comment]
Hey @Lachiven , solved when you changed what? :D

**Comment by Lachiven** [comment]
> Hey @Lachiven , solved when you changed what? :D

 Hey @FirasAbiFarraj ,I change the 
https://github.com/ethz-asl/segmap/blob/master/segmapper/launch/kitti/kitti_localization.launch#L31 
<node name="player" pkg="rosbag" type="play" output="screen" args=" -r $(arg play_rate) -s 333 --clock --pause $(arg bag_file)"/>  to <node name="player" pkg="rosbag" type="play" output="screen" args=" -r $(arg play_rate) -s 0 --clock --pause $(arg bag_file)"/>

**Comment by Lachiven** [comment]
node name="player" pkg="rosbag" type="play" output="screen" args=" -r $(arg play_rate) -s 333 --clock --pause $(arg bag_file)"/  
to
node name="player" pkg="rosbag" type="play" output="screen" args=" -r $(arg play_rate) -s 333 --clock --pause $(arg bag_file)"/

**Comment by Lachiven** [comment]
because the markdown something didn't show @FirasAbiFarraj  sorry about that.
and how do you relocalation with your own date. now I subscribe the tf of loam but works not as normal.
