### ISSUE TITLE
segmatch in windows

### ISSUE THREAD

**Issue by M1234Thomas** [ethz-asl/segmap#70]
Hello ,

Thank you for this great piece of work. 

I would like to integrate segmatch to another odometry algorithm but in windows environment.
What all changes in which all configuration files are necessary for this?

Can someone suggest any ideas or advices?

**Comment by rdube** [comment]
Hello @M1234Thomas, is it possible for you to use a virtual machine running Ubuntu? I would recommend that option as to run the laser_mapper you would have to first install ROS on windows..

**Comment by M1234Thomas** [comment]
Thank you so much fro your response. 

I am basically using Matlab for my algorithm implementation and my idea isto integrate SegMatch using Mex interface. So I would prefer it without a virtual machine.  Could you suggest the possible chnages to make it work. 

Thanks in advance,

**Comment by rdube** [comment]
What have you tried so far? Did you run into any specific issue?

**Comment by M1234Thomas** [comment]
I was trying to run the demo videos from windows. 
But I have troubles with the rviz file and the randomforest.xml files. Is it possible to reuse them in the wndows environment as well
