### ISSUE TITLE
demonstration problems

### ISSUE THREAD

**Issue by dshwtc** [ethz-asl/segmap#88]
The website "http://robotics.ethz.ch/~asl-datasets/segmap/" in wiki page for providing drive27_target_map.pcd and .rviz files is not avaliable for now, and it shows 403 Forbidden .
Are there other ways to get these files?

**Comment by smauq** [comment]
@dshwtc there was a power shutdown at the lab this morning. The server should be back up shortly.

**Comment by dshwtc** [comment]
Thanks!
