### ISSUE TITLE
the segmap catkin make

### ISSUE THREAD

**Issue by ytgcljj** [ethz-asl/segmap#91]
Errors     << gtsam_catkin:make /home/gtx-14/catkin_ws/logs/gtsam_catkin/build.make.006.log                                                                                                                 
CMake Error at CMakeLists.txt:297 (find_package):
  By not providing "Findmetis_catkin.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "metis_catkin", but CMake did not find one.

  Could not find a package configuration file provided by "metis_catkin" with
  any of the following names:

    metis_catkinConfig.cmake
    metis_catkin-config.cmake

  Add the installation prefix of "metis_catkin" to CMAKE_PREFIX_PATH or set
  "metis_catkin_DIR" to a directory containing one of the above files.  If
  "metis_catkin" provides a separate development package or SDK, be sure it
  has been installed.

make[2]: *** [gtsam_src-prefix/src/gtsam_src-stamp/gtsam_src-configure] 错误 1
make[1]: *** [CMakeFiles/gtsam_src.dir/all] 错误 2
make: *** [all] 错误 2
cd /home/gtx-14/catkin_ws/build/gtsam_catkin; catkin build --get-env gtsam_catkin | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
............................................................................................................................................................................................................
Failed     << gtsam_catkin:make                             [ Exited with code 2 ]                                                                                                                          
Failed    <<< gtsam_catkin                                  [ 0.2 seconds ]                                                                                                                                 
Abandoned <<< eigen_checks                                  [ Unrelated job failed ]                                                                                                                        
Abandoned <<< libpointmatcher                               [ Unrelated job failed ]                                                                                                                        
Abandoned <<< libpointmatcher_ros                           [ Unrelated job failed ]                                                                                                                        
Abandoned <<< ethzasl_icp_mapper                            [ Unrelated job failed ]                                                                                                                        
Abandoned <<< ethzasl_icp_mapper_experiments                [ Unrelated job failed ]                                                                                                                        
Abandoned <<< ethzasl_point_cloud_vtk_tools                 [ Unrelated job failed ]                                                                                                                        
Abandoned <<< minkindr                                      [ Unrelated job failed ]                                                                                                                        
Abandoned <<< minkindr_conversions                          [ Unrelated job failed ]                                                                                                                        
Abandoned <<< minkindr_gtsam                                [ Unrelated job failed ]                                                                                                                        
Abandoned <<< mincurves                                     [ Unrelated job failed ]                                                                                                                        
Abandoned <<< laser_slam                                    [ Unrelated job failed ]                                                                                                                        
Abandoned <<< laser_slam_ros                                [ Unrelated job failed ]                                                                                                                        
Abandoned <<< laser_slam_tools                              [ Unrelated job failed ]                                                                                                                        
Abandoned <<< segmatch                                      [ Unrelated job failed ]                                                                                                                        
Abandoned <<< segmatch_ros                                  [ Unrelated job failed ]                                                                                                                        
Abandoned <<< segmapper                                     [ Unrelated job failed ]                                                                                                                        
Abandoned <<< velodyne_assembler                            [ Unrelated job failed ]                                                                                                                        
____________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << libnabo:make /home/gtx-14/catkin_ws/logs/libnabo/build.make.005.log                                                                                                                           
Warning: Tag `SYMBOL_CACHE_SIZE' at line 289 of file /home/gtx-14/catkin_ws/build/libnabo/Doxyfile has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `SHOW_DIRECTORIES' at line 473 of file /home/gtx-14/catkin_ws/build/libnabo/Doxyfile has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: Tag `HTML_ALIGN_MEMBERS' at line 799 of file /home/gtx-14/catkin_ws/build/libnabo/Doxyfile has become obsolete.
To avoid this warning please remove this line from your configuration file or upgrade it using "doxygen -u"
Warning: doxygen no longer ships with the FreeSans font.
You may want to clear or change DOT_FONTNAME.

**Comment by ytgcljj** [comment]
thans @smauq

**Comment by 14212094** [comment]
can you give me your mailbox？I am a student in beijing，i have some problem too～Thank you
